// Signal v1 source list. ~50 handles spanning frontier-lab founders/researchers,
// AI Twitter commentators, tech VCs and operators, podcasters, and product/
// engineering voices. Edit this file to change Signal's coverage.

export const SIGNAL_HANDLES = [
  "sama",
  "tszzl",
  "ArfurRock",
  "signulll",
  "AndrewCurran_",
  "iruletheworldmo",
  "growing_daniel",
  "netcapgirl",
  "creatine_cycle",
  "ctjlewis",
  "nearcyan",
  "NickADobos",
  "nikitabier",
  "johncoogan",
  "deanwball",
  "patio11",
  "aidan_mclau",
  "dwarkesh_sp",
  "ns123abc",
  "anothercohen",
  "TheRealAdamG",
  "leerob",
  "kevinsxu",
  "tunguz",
  "alexrkonrad",
  "rauchg",
  "bnj",
  "karrisaarinen",
  "TheStalwart",
  "lennysan",
  "pitdesi",
  "scaling01",
  "citrini",
  "dylan522p",
  "bcherny",
  "stevehou",
  "thdxr",
  "thsottiaux",
  "pmarca",
  "trq212",
  "OfficialLoganK",
  "benhylak",
  "steipete",
  "polynoamial",
  "morqon",
  "garrytan",
  "MatthewBerman",
  "GergelyOrosz",
  "theo",
  "rileybrown",
  "ryolu_",
  "mitchellh",
] as const;

export type SignalHandle = (typeof SIGNAL_HANDLES)[number];
